# Generated by Django 5.2.4 on 2025-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(upload_to='loli/')),
                ('type', models.CharField(choices=[('NI', 'nigger'), ('CH', 'chmar'), ('BH', 'bhangi')], max_length=2)),
            ],
        ),
    ]
