# Generated by Django 5.2.4 on 2025-07-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_booking_exhibit_museum_ticket_visitor_delete_lol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='img',
        ),
        migrations.AddField(
            model_name='museum',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
