# Generated by Django 5.2.4 on 2025-07-26 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0005_visitor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['visit_date', 'booking_date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
